name: Simple Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    - name: Security Audit
      run: |
        if [ -f package.json ]; then
          npm audit --audit-level=high
        else
          echo "No dependencies to scan for vulnerabilities."
        fi
